/*
 * Use of this source code is governed by the MIT license that can be
 * found in the LICENSE file.
 */

package org.rust.lang.core.mir.dataflow.move;

import jakarta.annotation.Nonnull;
import org.rust.lang.core.mir.WithIndex;
import org.rust.lang.core.mir.schemas.MirLocation;

/**
 * MoveOut represents a point in a program that moves out of some L-value; i.e., "creates" uninitialized memory.
 *
 * With respect to dataflow analysis:
 * - Generated by moves and declaration of uninitialized variables.
 * - Killed by assignments to the memory.
 */
public class MoveOut implements WithIndex {
    private final int index;
    @Nonnull
    private final MovePath path;
    @Nonnull
    private final MirLocation source;

    public MoveOut(int index, @Nonnull MovePath path, @Nonnull MirLocation source) {
        this.index = index;
        this.path = path;
        this.source = source;
    }

    @Override
    public int getIndex() {
        return index;
    }

    @Nonnull
    public MovePath getPath() {
        return path;
    }

    @Nonnull
    public MirLocation getSource() {
        return source;
    }
}
