/*
 * Use of this source code is governed by the MIT license that can be
 * found in the LICENSE file.
 */

package org.rust.ide.clones;

import com.intellij.lang.LighterAST;
import com.intellij.lang.LighterASTNode;
import com.intellij.lang.LighterASTTokenNode;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.roots.ProjectFileIndex;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.tree.TokenSet;
import com.jetbrains.clones.configuration.DuplicateIndexConfiguration;
import com.jetbrains.clones.core.LighterAstNodeHashCache;
import com.jetbrains.clones.core.NodeHash;
import com.jetbrains.clones.core.CommonUtilsKt;
import com.jetbrains.clones.languagescope.common.CommonDuplicateScope;
import org.jetbrains.annotations.NotNull;
import org.rust.lang.core.parser.RustParserDefinition;
import org.rust.lang.core.psi.RsElementTypes;
import org.rust.lang.core.psi.RsTokenType;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import static org.rust.lang.core.psi.RsElementTypes.*;

public class RsDuplicateScope extends CommonDuplicateScope {

    private static final int VERSION = 1;

    private static final TokenSet NOISE = TokenSet.orSet(
        RsTokenType.RS_COMMENTS,
        TokenSet.create(
            TokenType.WHITE_SPACE,
            // Ignore trailing commas
            COMMA
        )
    );

    private static final TokenSet IGNORED = TokenSet.create(
        BLOCK,
        BLOCK_EXPR,
        MATCH_ARM,
        // TODO: probably we don't want to ignore members node because it can be generated by macro
        //  but it's here to avoid false positive annotations for now
        MEMBERS,
        WHERE_CLAUSE,
        VALUE_ARGUMENT_LIST, VALUE_PARAMETER_LIST,
        TYPE_ARGUMENT_LIST, TYPE_PARAMETER_LIST
    );

    /**
     * Presentable language name displayed in settings window
     * <p>
     * Used as a DuplicateScope id in settings serialization
     */
    @NotNull
    @Override
    public String getLanguageName() {
        return "Rust";
    }

    @Override
    public int getIndexVersion() {
        return RustParserDefinition.PARSER_VERSION + VERSION;
    }

    /**
     * @return true if {@code file} should be analyzed
     */
    @Override
    public boolean acceptsFile(@NotNull Project project, @NotNull VirtualFile file) {
        return ProjectFileIndex.getInstance(project).isInSourceContent(file);
    }

    /**
     * Defines how to compute hash of {@code node}
     *
     * @return true - based on tokenType
     * @return false - based on text
     */
    @Override
    public boolean isAnonymized(@NotNull LighterAST ast, @NotNull LighterASTTokenNode node) {
        NodeType nodeType = getNodeType(ast, node);
        switch (nodeType) {
            case LITERAL:
                return getIndexConfiguration().getAnonymizeLiterals();
            case IDENTIFIER:
                return getIndexConfiguration().getAnonymizeIdentifiers();
            case CALL:
            case METHOD_CALL:
            case FIELD:
                return getIndexConfiguration().getAnonymizeFunctions();
            case OTHER:
                return false;
            default:
                return false;
        }
    }

    /**
     * @param children nodes and hashes of immediate children.
     * @param cache    file-scoped cache of nodes hash; values must be saved explicitly.
     * @return normalized hash of supplied {@code node}. Equal nodes must have equal normalized hash.
     */
    @Override
    public long hashOf(
        LighterAstNodeHashCache cache,
        LighterAST ast,
        LighterASTNode node,
        List<? extends NodeHash> children
    ) {
        if (node.getTokenType() == BINARY_EXPR) {
            return getNormalizedHashOfBinaryExpr(ast, children);
        }
        return super.hashOf(cache, ast, node, children);
    }

    /**
     * @return true if given {@code node} should be excluded from report. Note that children still could be reported in this case.
     * To exclude children as well {@link #isNoise} method should return true
     */
    @Override
    public boolean isIgnoredAsDuplicate(@NotNull LighterAST ast, @NotNull LighterASTNode node) {
        return IGNORED.contains(node.getTokenType());
    }

    /**
     * @return true if the supplied {@code node} should be completely excluded from the analysis
     */
    @Override
    public boolean isNoise(@NotNull LighterAST ast, @NotNull LighterASTNode node) {
        return NOISE.contains(node.getTokenType());
    }

    /**
     * @return node weight, non-negative number. Used to compute total weight of code fragment.
     * Total duplicate weight is computed as sum of all node weights.
     * A duplicate is reported if total weight exceeds the user-specified threshold.
     * A code fragment is analyzed if total weight exceeds the {@link DuplicateIndexConfiguration#getWindowSize()}.
     */
    @Override
    public int weightOf(@NotNull LighterAST ast, @NotNull LighterASTNode node) {
        if (node.getTokenType() == BLOCK) {
            return 3;
        }
        // Weigh only leaf nodes. Otherwise, the inspection result depends on ast complexity
        // and it will show smaller code fragments
        if (node instanceof LighterASTTokenNode) {
            return 1;
        }
        return 0;
    }

    private NodeType getNodeType(LighterAST ast, LighterASTNode node) {
        IElementType tokenType = node.getTokenType();
        if (RsTokenType.RS_LITERALS.contains(tokenType)) {
            return NodeType.LITERAL;
        }
        if (tokenType == RsElementTypes.IDENTIFIER) {
            LighterASTNode parent = ast.getParent(node);
            if (parent == null) return NodeType.OTHER;
            IElementType parentType = parent.getTokenType();
            if (parentType == RsElementTypes.METHOD_CALL) {
                // x.method()
                //   ~~~~~~
                return NodeType.METHOD_CALL;
            } else if (parentType == FIELD_LOOKUP) {
                // x.field
                //   ~~~~~
                return NodeType.FIELD;
            } else if (parentType == PAT_BINDING) {
                // let variable = expr;
                //     ~~~~~~~~
                return NodeType.IDENTIFIER;
            } else if (parentType == PATH) {
                LighterASTNode grandParent = ast.getParent(parent);
                if (grandParent == null) return NodeType.OTHER;
                if (grandParent.getTokenType() != PATH_EXPR) return NodeType.OTHER;
                LighterASTNode greatGrandParent = ast.getParent(grandParent);
                if (greatGrandParent != null && greatGrandParent.getTokenType() == CALL_EXPR) {
                    return NodeType.CALL;
                }
                return NodeType.IDENTIFIER;
            } else {
                return NodeType.OTHER;
            }
        }
        return NodeType.OTHER;
    }

    private long getNormalizedHashOfBinaryExpr(LighterAST ast, List<? extends NodeHash> children) {
        if (children.size() != 3) return CommonUtilsKt.nodeListHash(children);
        NodeHash left = children.get(0);
        NodeHash op = children.get(1);
        NodeHash right = children.get(2);
        List<LighterASTNode> opChildren = ast.getChildren(op.getNode());
        IElementType opType = opChildren.size() == 1 ? opChildren.get(0).getTokenType() : null;

        if (opType == EQEQ || opType == EXCLEQ || opType == ANDAND || opType == OROR || opType == PLUS || opType == MUL) {
            // unorderedHash
            List<Long> hashes = new ArrayList<>();
            hashes.add(left.getHash());
            hashes.add(op.getHash());
            hashes.add(right.getHash());
            Collections.sort(hashes);
            return CommonUtilsKt.longHash(hashes);
        } else if (opType == GT) {
            return orderedHashOf(left, right, ">");
        } else if (opType == LT) {
            return orderedHashOf(right, left, ">");
        } else if (opType == GTEQ) {
            return orderedHashOf(left, right, ">=");
        } else if (opType == LTEQ) {
            return orderedHashOf(right, left, ">=");
        } else {
            return CommonUtilsKt.nodeListHash(children);
        }
    }

    private static long orderedHashOf(NodeHash left, NodeHash right, String sign) {
        List<Long> hashes = new ArrayList<>();
        if (left != null) hashes.add(left.getHash());
        if (right != null) hashes.add(right.getHash());
        hashes.add((long) sign.hashCode());
        return CommonUtilsKt.longHash(hashes);
    }

    private enum NodeType {
        LITERAL,
        CALL,
        METHOD_CALL,
        FIELD,
        IDENTIFIER,
        OTHER
    }
}
