/**
 * Language-agnostic foundations shared by every other module: the message bundle, collection and
 * process helpers, the graph types and the icon set. Nothing here knows what Rust is.
 */
open module consulo.rust.base {
    requires transitive consulo.rust.platform.compat;
    requires transitive java.desktop;
    requires transitive java.xml;
    requires transitive com.google.gson;
    requires transitive org.eclipse.jgit;
    requires transitive com.fasterxml.jackson.core;
    requires transitive com.fasterxml.jackson.annotation;
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.fasterxml.jackson.module.paramnames;
    requires transitive com.fasterxml.jackson.dataformat.toml;
    requires transitive kotlin.stdlib;
    requires transitive markdown.jvm;
    requires transitive semver.jvm;
    requires transitive org.apache.commons.lang3;
    requires transitive org.jdom;
    requires transitive consulo.annotation;
    requires transitive consulo.container.api;
    requires transitive consulo.disposer.api;
    requires transitive consulo.logging.api;
    requires transitive consulo.localize.api;
    requires transitive consulo.proxy;
    requires transitive consulo.base.localize.library;
    requires transitive consulo.base.icon.library;
    requires transitive consulo.platform.api;
    requires transitive consulo.util.collection;
    requires transitive consulo.util.concurrent;
    requires transitive consulo.util.dataholder;
    requires transitive consulo.util.io;
    requires transitive consulo.util.jdom;
    requires transitive consulo.util.lang;
    requires transitive consulo.util.xml.fast.reader;
    requires transitive consulo.util.xml.serializer;
    requires transitive consulo.ui.api;
    requires transitive consulo.ui.ex.api;
    requires transitive consulo.ui.ex.awt.api;
    requires transitive consulo.datacontext.api;
    requires transitive consulo.application.api;
    requires transitive consulo.application.content.api;
    requires transitive consulo.application.ui.api;
    requires transitive consulo.component.api;
    requires transitive consulo.component.store.api;
    requires transitive consulo.configurable.api;
    requires transitive consulo.index.io;
    requires transitive consulo.color.scheme.api;
    requires transitive consulo.document.api;
    requires transitive consulo.virtual.file.system.api;
    requires transitive consulo.virtual.file.watcher.api;
    requires transitive consulo.project.api;
    requires transitive consulo.project.content.api;
    requires transitive consulo.project.ui.api;
    requires transitive consulo.module.api;
    requires transitive consulo.module.content.api;
    requires transitive consulo.module.ui.api;
    requires transitive consulo.module.creation.api;
    requires transitive consulo.file.chooser.api;
    requires transitive consulo.file.editor.api;
    requires transitive consulo.file.template.api;
    requires transitive consulo.code.editor.api;
    requires transitive consulo.process.api;
    requires transitive consulo.execution.api;
    requires transitive consulo.execution.debug.api;
    requires transitive consulo.execution.test.api;
    requires transitive consulo.execution.test.sm.api;
    requires transitive consulo.language.api;
    requires transitive consulo.language.impl;
    requires transitive consulo.language.editor.api;
    requires transitive consulo.language.editor.refactoring.api;
    requires transitive consulo.language.editor.ui.api;
    requires transitive consulo.language.code.style.api;
    requires transitive consulo.language.code.style.ui.api;
    requires transitive consulo.language.spellchecker.api;
    requires transitive consulo.language.duplicate.analysis.api;
    requires transitive consulo.build.ui.api;
    requires transitive consulo.compiler.api;
    requires transitive consulo.find.api;
    requires transitive consulo.navigation.api;
    requires transitive consulo.usage.api;
    requires transitive consulo.undo.redo.api;
    requires transitive consulo.external.service.api;
    requires transitive consulo.external.system.api;
    requires transitive consulo.version.control.system.api;
    requires transitive consulo.http.api;
    requires consulo.ide.impl;
    requires transitive org.toml.lang;

    exports consulo.rust.icon;
    exports consulo.rust.localize;
    exports org.rust;
    exports org.rust.common.graph;
    exports org.rust.experiments;
    exports org.rust.icons;
    exports org.rust.colors;
    exports org.rust.notifications;
    exports org.rust.openapiext;
    exports org.rust.settings;
    exports org.rust.stdext;
    exports org.rust.util;
}
