/*
 * Use of this source code is governed by the MIT license that can be
 * found in the LICENSE file.
 */

package org.rust.ide.fixes;

import com.intellij.codeInsight.intention.FileModifier.SafeFieldForPreview;
import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.rust.ide.presentation.TypeRendering;
import org.rust.lang.core.psi.*;
import org.rust.lang.core.psi.ext.RsFunctionOrLambda;
import org.rust.lang.core.psi.ext.RsTraitRefUtil;
import org.rust.lang.core.types.*;
import org.rust.lang.core.types.ty.Ty;
import org.rust.lang.core.types.ty.TyAdt;

import java.util.Collections;

/**
 * Base class for converting the given expr to the type ty using a try-trait. The conversion process is
 * generated by a fromCallMaker function.
 */
abstract class ConvertToTyUsingTryTraitFix extends ConvertToTyUsingTraitFix {

    @SafeFieldForPreview
    private final Ty ty;
    @SafeFieldForPreview
    private final FromCallMaker fromCallMaker;

    public ConvertToTyUsingTryTraitFix(
        @NotNull RsExpr expr,
        @NotNull Ty ty,
        @NotNull String traitName,
        @NotNull FromCallMaker fromCallMaker
    ) {
        super(expr, ty, traitName);
        this.ty = ty;
        this.fromCallMaker = fromCallMaker;
    }

    @Override
    public void invoke(@NotNull Project project, @Nullable Editor editor, @NotNull RsExpr element) {
        RsPsiFactory psiFactory = new RsPsiFactory(project);
        RsExpr fromCall = fromCallMaker.make(psiFactory, element, ty);
        addFromCall(psiFactory, element, fromCall);
    }

    protected void addFromCall(@NotNull RsPsiFactory psiFactory, @NotNull RsExpr expr, @NotNull RsExpr fromCall) {
        expr.replace(fromCall);
    }

    @FunctionalInterface
    public interface FromCallMaker {
        RsExpr make(RsPsiFactory psiFactory, RsExpr expr, Ty ty);
    }
}
