/*
 * Use of this source code is governed by the MIT license that can be
 * found in the LICENSE file.
 */

package org.rust.ide.fixes;

import consulo.language.editor.inspection.FileModifier.SafeFieldForPreview;
import consulo.codeEditor.Editor;
import consulo.project.Project;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.rust.ide.presentation.TypeRendering;
import org.rust.lang.core.psi.*;
import org.rust.lang.core.psi.ext.RsFunctionOrLambda;
import org.rust.lang.core.psi.ext.RsTraitRefUtil;
import org.rust.lang.core.types.*;
import org.rust.lang.core.types.ty.Ty;
import org.rust.lang.core.types.ty.TyAdt;

import java.util.Collections;
import consulo.language.editor.inspection.FileModifier;

/**
 * Base class for converting the given expr to the type ty using a try-trait. The conversion process is
 * generated by a fromCallMaker function.
 */
abstract class ConvertToTyUsingTryTraitFix extends ConvertToTyUsingTraitFix {

    @SafeFieldForPreview
    private final Ty ty;
    @SafeFieldForPreview
    private final FromCallMaker fromCallMaker;

    public ConvertToTyUsingTryTraitFix(
        @Nonnull RsExpr expr,
        @Nonnull Ty ty,
        @Nonnull String traitName,
        @Nonnull FromCallMaker fromCallMaker
    ) {
        super(expr, ty, traitName);
        this.ty = ty;
        this.fromCallMaker = fromCallMaker;
    }

    @Override
    public void invoke(@Nonnull Project project, @Nullable Editor editor, @Nonnull RsExpr element) {
        RsPsiFactory psiFactory = new RsPsiFactory(project);
        RsExpr fromCall = fromCallMaker.make(psiFactory, element, ty);
        addFromCall(psiFactory, element, fromCall);
    }

    protected void addFromCall(@Nonnull RsPsiFactory psiFactory, @Nonnull RsExpr expr, @Nonnull RsExpr fromCall) {
        expr.replace(fromCall);
    }

    @FunctionalInterface
    public interface FromCallMaker {
        RsExpr make(RsPsiFactory psiFactory, RsExpr expr, Ty ty);
    }
}
